"""initial migration

Revision ID: 7ed7ed55ad0a
Revises:
Create Date: 2025-08-07 09:53:49.675969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ed7ed55ad0a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("text_ticket", sa.Text(), nullable=True),
        sa.Column("creating_ticket", sa.DateTime(), nullable=True),
        sa.Column("closing_ticket", sa.DateTime(), nullable=True),
        sa.Column("identifier", sa.String(), nullable=True),
        sa.Column("is_active", sa.String(), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("mail_users", sa.String(), nullable=True),
        sa.Column("is_admin", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("tickets")
    # ### end Alembic commands ###
